---
- name: Configuring machines into web server
  hosts: all
  become: true
  tasks:
    - name: Installing Apache2 into machines
      ansible.builtin.apt:
        name: apache2
        state: present
